[package]
name = "lib_14"
version = "0.1.0"
edition = "2021"

[lib]
# crate-type = ["lib"]
# crate-type = ["rlib"]
# crate-type = ["dylib"]
# crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
