[package]
name = "exe_16"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "^0.8.5"
futures = "^0.3.28"
# lib_14 = { path = "../../libraries/lib_14" }

# [dev-dependencies]
# lib_14 = { path = "../../libraries/lib_14" }
